name: Executer les tests cypress

on:
  push:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Installer les dependances
      run: npm install

    - name: Executer les tests
      run: npx cypress run